// <auto-generated />
namespace ProjetoFinal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Inicial3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inicial3));
        
        string IMigrationMetadata.Id
        {
            get { return "201706280316207_Inicial3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
